## vim: set fenc=utf-8 ts=4 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
##
## hyprtoolkit.conf by Andy3153
## created   10/04/26 ~ 18:07:09
##

source = ~/.config/hypr/colorschemes/common-colors-catppuccin-mocha.conf
source = ~/.config/hypr/colorschemes/catppuccin-hyprtoolkit/themes/mocha/catppuccin-mocha-blue.conf

accent_secondary = $select2
icon_theme = Papirus-Dark
