## vim: set fenc=utf-8 ts=4 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
##
## Common colors from Catppuccin Mocha by Andy3153
## created   10/04/26 ~ 18:53:29
##

source = ./catppuccin-hyprland/themes/mocha.conf


$fontAlpha  = $textAlpha
$font       = $text

$font2Alpha = $subtext1Alpha
$font2      = $subtext1


$bg0Alpha = $baseAlpha
$bg0      = $base

$bg1Alpha = 272737         # it's $base with lightness 16
$bg1      = rgb($bg1Alpha)

$bg2Alpha = $surface0Alpha
$bg2      = $surface0

$bg3Alpha = $surface1Alpha
$bg3      = $surface1


$C01Alpha    = 272F41
$C01         = rgb($C01Alpha)

$C02Alpha    = 303E5A
$C02         = rgb($C02Alpha)

$C03Alpha    = 415377
$C03         = rgb($C03Alpha)

$C04Alpha    = 52658E
$C04         = rgb($C04Alpha)

$C05Alpha    = 6B81B2
$C05         = rgb($C05Alpha)


$select1Alpha = $blueAlpha
$select1      = $blue

$select2Alpha = $lavenderAlpha
$select2      = $lavender

$select3Alpha = $mauveAlpha
$select3      = $mauve


$warnAlpha   = $yellowAlpha
$warn        = $yellow

$urgentAlpha = $redAlpha
$urgent      = $red

$goodAlpha   = $greenAlpha
$good        = $green
