## vim: set fenc=utf-8 ts=4 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
##
## Common colors from Catppuccin Mocha by Andy3153
## created   10/04/26 ~ 18:53:29
##

source = ./catppuccin-hyprland/themes/mocha.conf


$fg0 = $textAlpha
$fg1 = $subtext1Alpha
$fg2 = $overlay1Alpha
$fg3 = $overlay0Alpha

$bg0 = $baseAlpha
$bg1 = 272737
$bg2 = $surface0Alpha
$bg3 = $surface1Alpha
$bg4 = $surface2Alpha

$select0 = $blueAlpha
$select1 = $lavenderAlpha
$select2 = $mauveAlpha

$warn   = $yellowAlpha
$urgent = $redAlpha
$good   = $greenAlpha
