#!/usr/bin/env sh
## vim: set fenc=utf-8 ts=2 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
##
## launch-kdepolkitagent by Andy3153
## created   15/06/24 ~ 14:49:17
##
## Launch KDE's Polkit authentication agent on different distros
## It's usually not in $PATH that's why, and NixOS is NixOS
##

isOS()
{
  grep -i "$@" /etc/lsb-release 2> /dev/null
}

if isOS "nixos"
then
  dir=$(
    for f in /nix/store/*polkit-kde-agent*
    do
      if [ -d "${f}" ]
      then echo "${f}" | head -n1
      fi
    done
  )

  "${dir}/libexec/polkit-kde-authentication-agent-1"

elif isOS "arch"
then /usr/lib/polkit-kde-authentication-agent-1
fi
